sudo: false
cache: false
language: android
jdk: oraclejdk8
android:
    components:
        - tools
        - build-tools-28.0.2
        - android-27
        - extra-google-m2repository
        - extra-android-m2repository
script:
    - TERM=dumb ./gradlew lint testDebugUnitTest jacocoTestDebugUnitTestReport
before_install:
    - chmod +x gradlew
    - yes | sdkmanager "platforms;android-27"
after_success:
    - bash <(curl -s https://codecov.io/bash)
